version: '2.1'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        build: .
        container_name: airflow
        #restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        volumes:
            - ./dags:/root/home/dags
            - ./conf:/root/home/conf
        ports:
            - "8080:8080"
        command: ["webserver"]
        healthcheck:
            test: ["CMD-SHELL", "[ -f /root/home/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

